# Generated by Django 3.1 on 2020-10-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201030_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagem',
            options={},
        ),
    ]
